import { flatten } from './util'

/**
 * How to read the response body. Omit it and the `content-type` decides: json is parsed, anything else
 * comes back as text.
 *
 * - `json` / `text` — parse, or take the raw text
 * - `blob` / `arraybuffer` — binary downloads (an attachment, a generated document)
 * - `document` — returns the **text**, not a DOM. `DOMParser` is browser-only and this runs under SSR
 *   too, so parsing is the caller's job
 */
export type HttpResponseType = 'json' | 'text' | 'blob' | 'arraybuffer' | 'document'

export interface RequestOptions {
  /**
   * Query parameters. An array value repeats the key (`{ code: ['a', 'b'] }` → `?code=a&code=b`) and
   * `undefined` values are dropped, so an optional filter can be passed unconditionally.
   */
  params?: Record<string, any>
  /**
   * Request headers. An explicit `undefined` value *removes* a header the transport would otherwise
   * add — that is how a multipart upload drops `Content-Type` so the boundary can be generated.
   */
  headers?: Record<string, any>
  /** how to read the response body; defaults to the `content-type` — see {@link HttpResponseType} */
  responseType?: HttpResponseType | string

  /** `RequestInit` fields — `credentials`, `signal`, `mode`, … — are forwarded as-is; see `INIT_KEYS` */
  [x: string]: any
}

/** `RequestInit` fields a caller may pass straight through — the `[x: string]: any` index on
 * `RequestOptions` would otherwise swallow them silently. */
const INIT_KEYS = ['credentials', 'mode', 'redirect', 'cache', 'signal', 'integrity', 'keepalive', 'referrer'] as const

const buildQuery = (params?: Record<string, any>) => {
  if (!params) return ''
  const encoded = new URLSearchParams()
  Object.entries(params).forEach(([key, value]) => {
    if (Array.isArray(value)) {
      value.forEach(val => {
        if (typeof val !== 'undefined') encoded.append(key, String(val))
      })
    } else if (typeof value !== 'undefined') {
      encoded.append(key, String(value))
    }
  })
  const query = encoded.toString()
  return (query && `?${query}`) || ''
}

const buildBody = (body: unknown): { body: BodyInit; contentType?: string } | undefined => {
  if (body === null || body === undefined) return undefined
  if (body instanceof URLSearchParams) return { body: body.toString(), contentType: 'application/x-www-form-urlencoded' }
  // FormData must not carry an explicit Content-Type — the boundary is generated by the transport
  if (body instanceof FormData || body instanceof Blob || body instanceof ArrayBuffer) return { body: body as BodyInit }
  if (typeof body === 'string') return { body }
  return { body: JSON.stringify(body), contentType: 'application/json' }
}

const tryJson = (text: string) => {
  try {
    return JSON.parse(text)
  } catch {
    return text
  }
}

const parseBody = async (response: Response, responseType?: string) => {
  if (response.status === 204) return undefined
  switch (responseType) {
    case 'blob':
      return await response.blob()
    case 'arraybuffer':
      return await response.arrayBuffer()
    // 'document' stays text — DOM parsing is browser-only, so the caller owns it
    case 'text':
    case 'document':
      return (await response.text()) || undefined
  }
  const contentType = response.headers.get('content-type') || ''
  if (contentType.includes('json')) return await response.json().catch(() => undefined)
  return (await response.text()) || undefined
}

/**
 * Thrown when the server answered with a non-2xx.
 *
 * A real `Error`, so it carries a stack and logs as one. It is also the only way a caller can tell the
 * three cases in a `catch` apart: `instanceof RestError` means the server answered and refused —
 * anything else means the request never got a response (`fetch` rejects with a `TypeError`) or the
 * handler itself threw. Rethrow what is not a `RestError` rather than swallowing it.
 *
 * @example
 * ```ts
 * try {
 *   await client.postAt(`${cartId}/vouchers`, voucher)
 * } catch (e) {
 *   if (!(e instanceof RestError)) throw e
 *   if (e.status === 409) return
 *   message = e.body?.errors?.map((x: any) => x.message).join(', ') ?? ''
 * }
 * ```
 */
export class RestError<T = any> extends Error {
  constructor(
    /** the http status the server answered with */
    readonly status: number,
    /** the reason phrase — often `''`, since http/2 drops them */
    readonly statusText: string,
    /** the url as this client built it, query string included */
    readonly url: string,
    /** parsed when the response was json, the raw text otherwise, `undefined` when the body was empty */
    readonly body: T | undefined
  ) {
    // http/2 drops reason phrases, so statusText is often ''
    super(`${status}${(statusText && ` ${statusText}`) || ''} — ${url}`)
    this.name = 'RestError'
  }
}

const toError = async (response: Response, url: string) => {
  // one read only — the body is a stream, so parsing json and then falling back to text would drain it
  const text = await response.text().catch(() => '')
  return new RestError(response.status, response.statusText, url, (text && tryJson(text)) || undefined)
}

const toUrlForm = (body: Record<string, any>): URLSearchParams => {
  const params = new URLSearchParams()
  Object.keys(body).forEach(k => {
    if (body[k]) params.append(k, body[k])
  })
  return params
}

const toFormData = (body: Record<string, any>): FormData => {
  const formData = new FormData()
  const flattened = flatten(body, [File, Blob, Date])
  Object.entries(flattened).forEach(([key, value]) => {
    if (value !== null && value !== undefined) {
      if (value instanceof Date) {
        formData.append(key, value.toISOString())
      } else {
        formData.append(key, value)
      }
    }
  })
  return formData
}

/**
 * The client {@link rest} returns — one endpoint's verbs. Use it to type a consumer that takes a client
 * rather than restating the shape.
 */
export interface RestClient {
  /**
   * `GET` the endpoint itself — the list, not a member of it.
   * @throws {RestError} on a non-2xx
   * @example `client.query<ProductList>({ params: { fields: 'FULL', pageSize: 20 } })`
   */
  query: <T>(options?: RequestOptions) => Promise<T>
  /** `HEAD` `endpoint/{id}` — always resolves `undefined`; use it for the status alone. @throws {RestError} */
  head: <T>(id: number | string, options?: RequestOptions) => Promise<T>
  /**
   * `GET` `endpoint/{id}`. `id` is any path suffix, not only a bare identifier — `'123/references'`
   * and `'sessions/abc/detail'` are both fine.
   * @throws {RestError} on a non-2xx, 404 included
   */
  get: <T>(id: number | string, options?: RequestOptions) => Promise<T>
  /** `POST` to the endpoint itself — create. @throws {RestError} */
  post: <T>(body: any, options?: RequestOptions) => Promise<T>
  /** `POST` to `endpoint/{id}` — an action on a member (`addVoucher`, `cancellation`). @throws {RestError} */
  postAt: <T>(id: number | string, body: any, options?: RequestOptions) => Promise<T>
  /** `PUT` `endpoint/{id}` — full replace. @throws {RestError} */
  put: <T>(id: number | string, body: any, options?: RequestOptions) => Promise<T>
  /** `PATCH` `endpoint/{id}` — partial update. @throws {RestError} */
  patch: <T>(id: number | string, body: any, options?: RequestOptions) => Promise<T>
  /** `DELETE` `endpoint/{id}` — resolves `undefined` on the usual 204. @throws {RestError} */
  delete: <T>(id: number | string, options?: RequestOptions) => Promise<T>
  /**
   * Flat object → `URLSearchParams`, for the endpoints that want a form post rather than json.
   * Falsy values are dropped, so an absent optional field sends nothing rather than `''`.
   *
   * @example
   * ```ts
   * client.postAt(`${groupId}/members`, client.toUrlForm({ customerId }))
   * ```
   */
  toUrlForm: (body: Record<string, any>) => URLSearchParams
  /**
   * Object → `FormData`, flattening nested objects to dotted keys (`{ nested: { id: 5 } }` →
   * `nested.id=5`). `File`, `Blob` and `Date` survive whole — `Date` as an ISO string — and
   * `null`/`undefined` entries are skipped.
   */
  toFormData: (body: Record<string, any>) => FormData
}

/**
 * A REST client bound to one endpoint: the verbs build urls under it, serialise the body by its type,
 * parse the response, and throw {@link RestError} on a non-2xx.
 *
 * Body serialisation follows the value: `FormData`/`Blob`/`ArrayBuffer` go through untouched (no
 * `Content-Type`, so the transport can add the multipart boundary), `URLSearchParams` becomes
 * form-urlencoded, a string is sent as-is, and anything else is JSON.
 *
 * Interceptors, auth and retries are not this client's job — they belong to the `doFetch` it is handed.
 *
 * @param endpoint the absolute base url, or a thunk resolving it — read config/route state lazily in
 *   the thunk, so a client built once still follows the site, locale and user path as they change
 * @param doFetch `fetch`-compatible transport — a {@link FetchClient}'s `fetch`, plain `fetch`, or a mock
 *
 * @example A resource built once, following the context
 * ```ts
 * const client = rest(() => `${sitePath}/users/${userId}/carts`, api.fetch)
 * await client.get('300938', { params: { fields: 'FULL' } })
 * ```
 */
export const rest = (endpoint: string | (() => string), doFetch: typeof fetch = fetch): RestClient => {
  const base = (typeof endpoint === 'function' && endpoint) || (() => endpoint as string)
  const request = async <T>(method: string, url: string, body?: unknown, options?: RequestOptions): Promise<T> => {
    const headers = new Headers()
    Object.entries(options?.headers || {}).forEach(([key, value]) => {
      // an explicit `undefined` clears a default (multipart uploads drop Content-Type)
      if (value !== undefined && value !== null) headers.set(key, String(value))
    })
    const init: RequestInit = { method }
    INIT_KEYS.forEach(key => {
      if (options?.[key] !== undefined) (init as Record<string, unknown>)[key] = options[key]
    })
    const built = buildBody(body)
    if (built) {
      init.body = built.body
      if (built.contentType && !headers.has('Content-Type')) headers.set('Content-Type', built.contentType)
    }
    init.headers = headers
    // the url we built, not `response.url` — a redirect or a mocked Response would report a different one
    const fullUrl = `${url}${buildQuery(options?.params)}`
    const response = await doFetch(fullUrl, init)
    if (!response.ok) throw await toError(response, fullUrl)
    if (method === 'HEAD') return undefined as T
    return (await parseBody(response, options?.responseType)) as T
  }

  return {
    query: <T>(options?: RequestOptions) => request<T>('GET', base(), undefined, options),
    head: <T>(id: number | string, options?: RequestOptions) => request<T>('HEAD', `${base()}/${id}`, undefined, options),
    get: <T>(id: number | string, options?: RequestOptions) => request<T>('GET', `${base()}/${id}`, undefined, options),
    post: <T>(body: any, options?: RequestOptions) => request<T>('POST', base(), body, options),
    postAt: <T>(id: number | string, body: any, options?: RequestOptions) => request<T>('POST', `${base()}/${id}`, body, options),
    put: <T>(id: number | string, body: any, options?: RequestOptions) => request<T>('PUT', `${base()}/${id}`, body, options),
    patch: <T>(id: number | string, body: any, options?: RequestOptions) => request<T>('PATCH', `${base()}/${id}`, body, options),
    delete: <T>(id: number | string, options?: RequestOptions) => request<T>('DELETE', `${base()}/${id}`, undefined, options),
    toUrlForm,
    toFormData
  }
}
